# Generated by Django 5.1.1 on 2025-02-13 21:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.CharField(max_length=10, unique=True)),
                ('scara', models.CharField(blank=True, max_length=100, null=True)),
                ('etaj', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Apartament',
                'verbose_name_plural': 'Apartamente',
            },
        ),
        migrations.CreateModel(
            name='Aviz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avize', models.TextField(default='Default content')),
                ('titlu', models.CharField(max_length=100)),
                ('continut', models.TextField()),
                ('data_postarii', models.DateTimeField(default=django.utils.timezone.now)),
                ('eta', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aviz',
                'verbose_name_plural': 'Avize',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturiIntretinere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luna', models.DateField(default=django.utils.timezone.now)),
                ('pdf_factura', models.FileField(default='default.pdf', upload_to='locatari/lista_facturi/')),
                ('contor_valoare', models.FloatField(default=0.0)),
                ('suma_plata', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_adaugarii', models.DateTimeField(default=django.utils.timezone.now)),
                ('achitata', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatari.apartament')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturi',
            },
        ),
        migrations.CreateModel(
            name='Locatari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locatari.apartament')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatari.index')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamatii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('noise', 'Noise'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=50)),
                ('titlu', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamatie',
                'verbose_name_plural': 'Reclamatii',
            },
        ),
        migrations.CreateModel(
            name='WaterMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('hot_water_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cold_water_index', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apartament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locatari.apartament')),
            ],
        ),
    ]
